import { useState } from 'react';
import { useAuth } from '../context/AuthContext.jsx';

const symptomOptions = ['Headache', 'Fatigue', 'Cough', 'Sore throat', 'Nausea', 'Fever'];
export default function DiagnosisForm({ onBack }) {
  const { user } = useAuth(); const [symptoms, setSymptoms] = useState([]); const [form, setForm] = useState({ duration: '', severity: '', notes: '' }); const [submitted, setSubmitted] = useState(false);
  const toggle = (symptom) => setSymptoms((current) => current.includes(symptom) ? current.filter((item) => item !== symptom) : [...current, symptom]);
  const submit = async (event) => { event.preventDefault(); const payload = { symptoms, ...form }; try { await fetch('http://localhost:5000/api/diagnoses', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${localStorage.getItem('carepath_token')}` }, body: JSON.stringify(payload) }); } catch { /* Demo mode keeps the flow available without the API. */ } setSubmitted(true); };
  if (submitted) return <main className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark">+</span> carepath</div><button className="signout" onClick={onBack}>Back to overview</button></header><section className="result-page"><div className="result-icon">+</div><p className="eyebrow">CHECK-IN RECEIVED</p><h1>Thank you for checking in, {user?.name?.split(' ')[0] || 'there'}.</h1><p className="muted">Your answers have been recorded. Based on what you shared, take some time to rest and monitor how you feel.</p><button className="primary" onClick={onBack}>Return to overview <span>-&gt;</span></button></section></main>;
  return <main className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark">+</span> carepath</div><button className="signout" onClick={onBack}>Cancel</button></header><section className="form-page"><div className="form-intro"><p className="eyebrow">NEW CHECK-IN</p><h1>Tell us how you’re feeling.</h1><p className="muted">Answer a few questions to create a personal starting point. This is not a medical diagnosis.</p></div><form className="checkin-form" onSubmit={submit}><fieldset><legend>What are you experiencing?</legend><p className="field-hint">Select all that apply.</p><div className="symptoms">{symptomOptions.map((symptom) => <button type="button" className={symptoms.includes(symptom) ? 'symptom selected' : 'symptom'} onClick={() => toggle(symptom)} key={symptom}>{symptoms.includes(symptom) ? '✓ ' : '+ '}{symptom}</button>)}</div></fieldset><label>How long have you felt this way?<select required value={form.duration} onChange={(e) => setForm({ ...form, duration: e.target.value })}><option value="">Choose duration</option><option>Less than a day</option><option>1–3 days</option><option>More than a week</option></select></label><fieldset><legend>How would you describe the severity?</legend><div className="severity-options">{['mild', 'moderate', 'severe'].map((level) => <label className={`severity ${form.severity === level ? 'selected' : ''}`} key={level}><input type="radio" name="severity" required value={level} checked={form.severity === level} onChange={(e) => setForm({ ...form, severity: e.target.value })} /><span><strong>{level[0].toUpperCase() + level.slice(1)}</strong><small>{level === 'mild' ? 'Manageable' : level === 'moderate' ? 'Affecting my day' : 'Hard to manage'}</small></span></label>)}</div></fieldset><label>Anything else you’d like to share? <span className="optional">Optional</span><textarea value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} placeholder="Add context about how you’re feeling..." /></label><button className="primary submit-button" type="submit" disabled={!symptoms.length}>Review my check-in <span>-&gt;</span></button></form></section></main>;
}
